### ISSUE TITLE
Errors for certain values horizon and window lengths in operate mode

### ISSUE THREAD

**Issue by ahilbers** [calliope-project/calliope#337]
## Problem description

I've found some strange behaviour when using different horizon and window lengths in `operate` mode. In particular, I get errors (that I believe are bugs) in the following situations:
- when the horizon is longer than the full time series, and the window is shorter than the horizon
- when the horizon and window are the same length, both shorter than the full time series and not dividing the full time series length.

These errors come from `pandas` when creating the time series for the model runs in `operate` mode.

## Steps to reproduce the problem

I've created a simple test setting, based on the `model_minimal.yaml` model in the tests, that has this behaviour. To recreate it, put the following files in a directory:
- `model.yaml`:
- `demand_elec.csv`: same as  `calliope/calliope/test/common/test_model/timeseries_data/demand_elec.csv`, but just the first 5 days (`2005-01-01`:`2005-01-05`)
- `main.py`: python code to recreate the problem.

The files are:

```
## model.yaml

model:
    name: Operate model
    timeseries_data_path: ''

run:
    mode: operate
    solver: cbc
    objective_options:
        cost_class:
            monetary: 1
    cyclic_storage: False

techs:
    test_supply_elec:
        essentials:
            name: Supply tech
            carrier: electricity
            parent: supply
        constraints:
            energy_cap_max: 10
            resource: .inf
            lifetime: 25
        costs:
            monetary:
                interest_rate: 0.1      
                energy_cap: 20
                om_con: 0.1
    test_demand_elec:
        essentials:
            name: Demand elec tech
            carrier: electricity
            parent: demand
        constraints:
            resource: file=demand_elec.csv

locations:
    0:
        techs:
            test_supply_elec:
            test_demand_elec:
```
```
## main.py

import calliope

horizon = 24    # change these values
window = 24    # change these values

override_dict = {"run.operation.horizon": horizon,
                 "run.operation.window": window}
model = calliope.Model("model.yaml", override_dict=override_dict)
model.run()
```

When I call `main.py` with different values of `window` and `horizon`, I get the following tracebacks. Note that the total time series length is 5 days, so 120 hours.

```
# horizon=144, window=24

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    model.run()
  File "/Users/aph416/opt/anaconda3/envs/calliope/lib/python3.8/site-packages/calliope/core/model.py", line 243, in run
    results, self._backend_model, interface = run_backend(
  File "/Users/aph416/opt/anaconda3/envs/calliope/lib/python3.8/site-packages/calliope/backend/run.py", line 55, in run
    results, backend = run_operate(
  File "/Users/aph416/opt/anaconda3/envs/calliope/lib/python3.8/site-packages/calliope/backend/run.py", line 227, in run_operate
    end_timestep = horizon_ends.index[i]
  File "/Users/aph416/opt/anaconda3/envs/calliope/lib/python3.8/site-packages/pandas/core/indexes/datetimes.py", line 1220, in __getitem__
    result = self._data.__getitem__(key)
  File "/Users/aph416/opt/anaconda3/envs/calliope/lib/python3.8/site-packages/pandas/core/arrays/datetimelike.py", line 426, in __getitem__
    val = getitem(key)
IndexError: index 0 is out of bounds for axis 0 with size 0
```

```
horizon=48, window=48

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    model.run()
  File "/Users/aph416/opt/anaconda3/envs/calliope/lib/python3.8/site-packages/calliope/core/model.py", line 243, in run
    results, self._backend_model, interface = run_backend(
  File "/Users/aph416/opt/anaconda3/envs/calliope/lib/python3.8/site-packages/calliope/backend/run.py", line 55, in run
    results, backend = run_operate(
  File "/Users/aph416/opt/anaconda3/envs/calliope/lib/python3.8/site-packages/calliope/backend/run.py", line 274, in run_operate
    var_series.index = backend_model.__calliope_model_data['data'][var].keys()
  File "/Users/aph416/opt/anaconda3/envs/calliope/lib/python3.8/site-packages/pandas/core/generic.py", line 5192, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__
  File "/Users/aph416/opt/anaconda3/envs/calliope/lib/python3.8/site-packages/pandas/core/series.py", line 444, in _set_axis
    self._data.set_axis(axis, labels)
  File "/Users/aph416/opt/anaconda3/envs/calliope/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 181, in set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 24 elements, new values have 48 elements
```

After trying a larger set of horizon and window values, I get the following results:

```
   window horizon      result
0      24      24          OK
1      24      48          OK
2      24      72          OK
3      24      96          OK
4      24     120          OK
5      24     144  IndexError
6      48      48  ValueError
7      48      72          OK
8      48      96          OK
9      48     120          OK
10     48     144  IndexError
11     72      72  ValueError
12     72      96          OK
13     72     120          OK
14     72     144  IndexError
15     96      96  ValueError
16     96     120          OK
17     96     144  IndexError
18    120     120          OK
19    120     144  IndexError
20    144     144          OK
21    144     168  IndexError
```

## Calliope version

0.6.5 (the result is the same with 0.6.6).

**Comment by ahilbers** [comment]
I believe that I've fixed these issues with some small changes to how the `pandas` dataframes are sliced, as in the pull request above. Let me know what you think!

**Comment by lblabr** [comment]
> I believe that I've fixed these issues with some small changes to how the `pandas` dataframes are sliced, as in the pull request above. Let me know what you think!

i have the same error, how do i use your fix ?

**Comment by ahilbers** [comment]
@lblabr I think that if you change one file in the calliope directory, it should work. To do this, you have to change the file `$YOUR_CALLIOPE_LOCATION/calliope/backend/run.py`. Just copy pasting this one in: https://github.com/ahilbers/calliope/blob/operate_horizon_window_bug/calliope/backend/run.py should work.

FYI for me, $YOUR_CALLIOPE_LOCATION is `/Users/$USERNAME/opt/anaconda3/envs/calliope/lib/python3.8/site-packages/calliope` -- that's where it installs on a mac using anaconda.

Let me know if copy pasting this in works and solves your problem.

**Comment by ahilbers** [comment]
@sjpfenninger @brynpickering Will you guys have a chance to have a look at this anytime soon? Other users appear to getting this issue too (see @lblabr above).

**Comment by lblabr** [comment]
thank's a lot!
